// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_MEPz08cdGbXSE7-s5TOJc7Sb92jcfvc',
    appId: '1:1055082590155:web:44a39351e63e3b9ffd504e',
    messagingSenderId: '1055082590155',
    projectId: 'inventory-count-app-jao',
    authDomain: 'inventory-count-app-jao.firebaseapp.com',
    storageBucket: 'inventory-count-app-jao.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVRREIwsqM_4B_qDVy-dgTlG1J09OEt_4',
    appId: '1:1055082590155:android:79b8cc4f33efa1bcfd504e',
    messagingSenderId: '1055082590155',
    projectId: 'inventory-count-app-jao',
    storageBucket: 'inventory-count-app-jao.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxn3m_9qgyQ98zI7mOVltiGPgv7L0h97k',
    appId: '1:1055082590155:ios:f4fcee33f7682d9cfd504e',
    messagingSenderId: '1055082590155',
    projectId: 'inventory-count-app-jao',
    storageBucket: 'inventory-count-app-jao.firebasestorage.app',
    iosBundleId: 'com.jao.inventoryCountApp',
  );
}
